export type ToolInputType = "file" | "directory" | "text" | "url" | "select" | "confirm" | "number";
export type EnvRequirement = "adb" | "java" | "git" | "fastboot";
export type DeviceMode = "adb" | "fastboot" | "all" | "none";

export interface ToolInput {
  id: string;
  type: ToolInputType;
  label: string;
  placeholder?: string;
  fileFilters?: { name: string; extensions: string[] }[];
  options?: { value: string; label: string }[];
  required: boolean;
  defaultValue?: string;
}

export interface ToolDefinition {
  id: string;
  name: string;
  description: string;
  category: string;
  subcategory?: string;
  scriptPath: string;
  icon: string;
  inputs: ToolInput[];
  requiresDevice: boolean;
  deviceMode: DeviceMode;
  multipleDevices: boolean;
  requiredEnv: EnvRequirement[];
  postInputs?: string[];
  postDelayMs?: number;
}

export interface ToolCategory {
  id: string;
  name: string;
  icon: string;
  subcategories?: { id: string; name: string }[];
}

export const toolCategories: ToolCategory[] = [
  {
    id: "device",
    name: "设备工具",
    icon: "Smartphone",
    subcategories: [
      { id: "device-basic", name: "基础" },
      { id: "device-simulation", name: "模拟" },
      { id: "device-env", name: "环境" },
      { id: "device-hardware", name: "硬件" },
      { id: "device-jump", name: "跳转" },
      { id: "device-flash", name: "刷机" },
    ],
  },
  {
    id: "reverse",
    name: "逆向工具",
    icon: "Code",
    subcategories: [
      { id: "reverse-apktool", name: "APKTool" },
      { id: "reverse-viewer", name: "查看器" },
      { id: "reverse-convert", name: "格式转换" },
    ],
  },
  {
    id: "package",
    name: "包体工具",
    icon: "Package",
  },
  {
    id: "git",
    name: "Git 工具",
    icon: "GitBranch",
    subcategories: [
      { id: "git-repo", name: "仓库" },
      { id: "git-config", name: "配置" },
      { id: "git-commit", name: "提交" },
      { id: "git-push", name: "推送" },
    ],
  },
  {
    id: "ssh-key",
    name: "密钥工具",
    icon: "Key",
  },
];

export const tools: ToolDefinition[] = [
  // ─── Device - Basic ──────────────────────────────────────────────────
  {
    id: "install-apk",
    name: "安装 APK",
    description: "将 APK 文件安装到连接的设备",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/InstallApk.sh",
    icon: "Download",
    inputs: [
      {
        id: "sourcePath",
        type: "file",
        label: "APK 文件或目录",
        fileFilters: [{ name: "APK", extensions: ["apk"] }],
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "uninstall-app",
    name: "卸载应用",
    description: "从设备上卸载指定应用",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/UninstallApp.sh",
    icon: "Trash2",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        placeholder: "com.example.app",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "set-global-proxy",
    name: "设置全局代理",
    description: "为设备设置全局 HTTP 代理",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/SetGlobalProxy.sh",
    icon: "Globe",
    inputs: [
      {
        id: "host",
        type: "text",
        label: "代理地址",
        placeholder: "192.168.1.100",
        required: true,
      },
      {
        id: "port",
        type: "text",
        label: "代理端口",
        placeholder: "8888",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "clear-global-proxy",
    name: "清除全局代理",
    description: "清除设备上的全局 HTTP 代理",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ClearGlobalProxy.sh",
    icon: "XCircle",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "save-screenshot",
    name: "截图保存",
    description: "截取设备屏幕并保存到本地",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/SaveScreenshot.sh",
    icon: "Camera",
    inputs: [
      {
        id: "targetDir",
        type: "directory",
        label: "保存目录",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "save-screen-recording",
    name: "录屏保存",
    description: "录制设备屏幕并保存到本地",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/SaveScreenRecording.sh",
    icon: "Video",
    inputs: [
      {
        id: "targetDir",
        type: "directory",
        label: "保存目录",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "manage-file",
    name: "管理文件",
    description: "管理设备上的文件（推送/拉取）",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ManageFile.sh",
    icon: "FolderOpen",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "connect-wireless-adb",
    name: "开启无线调试",
    description: "通过 Wi-Fi 连接设备进行 ADB 调试",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ConnectWirelessAdb.sh",
    icon: "Wifi",
    inputs: [
      {
        id: "port",
        type: "text",
        label: "端口号",
        placeholder: "5555",
        defaultValue: "5555",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "disconnect-wireless-adb",
    name: "关闭无线调试",
    description: "断开无线 ADB 连接",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/DisconnectWirelessAdb.sh",
    icon: "WifiOff",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "get-top-activity-package",
    name: "获取栈顶包名",
    description: "获取当前屏幕前台应用的包名和 Activity",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetTopActivityPackage.sh",
    icon: "Layers",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "get-top-activity-content",
    name: "获取栈顶内容",
    description: "获取当前屏幕前台 Activity 的视图层级内容",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetTopActivityContent.sh",
    icon: "FileText",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "export-apk-file",
    name: "导出 APK",
    description: "从设备中导出已安装应用的 APK 文件",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ExportApkFile.sh",
    icon: "FileOutput",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名 (留空导出全部)",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "export-anr-file",
    name: "导出 ANR",
    description: "从设备导出 ANR（应用无响应）日志文件",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ExportAnrFile.sh",
    icon: "Bug",
    inputs: [
      {
        id: "exportDir",
        type: "directory",
        label: "导出目录",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "clear-app-data",
    name: "清除应用数据",
    description: "清除指定应用的所有数据和缓存",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/ClearAppData.sh",
    icon: "Eraser",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "kill-app-process",
    name: "杀死应用进程",
    description: "强制停止指定应用进程",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/KillAppProcess.sh",
    icon: "Square",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "disabled-app",
    name: "禁用应用",
    description: "禁用设备上的指定应用",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/DisabledApp.sh",
    icon: "Ban",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "enabled-app",
    name: "启用应用",
    description: "启用设备上被禁用的应用",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/EnabledApp.sh",
    icon: "CheckCircle",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "grant-permission",
    name: "授予权限",
    description: "为指定应用授予特定权限",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GrantPermission.sh",
    icon: "ShieldCheck",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
      {
        id: "permission",
        type: "text",
        label: "权限名",
        placeholder: "android.permission.CAMERA",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "revoke-permission",
    name: "撤销权限",
    description: "撤销指定应用的特定权限",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/RevokePermission.sh",
    icon: "ShieldOff",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
      {
        id: "permission",
        type: "text",
        label: "权限名",
        placeholder: "android.permission.CAMERA",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "get-screen-info",
    name: "获取屏幕信息",
    description: "获取设备屏幕分辨率、密度等信息",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetScreenInfo.sh",
    icon: "Monitor",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "get-system-properties",
    name: "获取系统属性",
    description: "获取设备的系统属性信息",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetSystemProperties.sh",
    icon: "Info",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "get-device-serial-no",
    name: "获取设备序列号",
    description: "获取连接设备的序列号",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetDeviceSerialNo.sh",
    icon: "Hash",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "get-device-cpu-abi",
    name: "获取 CPU 架构",
    description: "获取设备的 CPU ABI 架构信息",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/GetDeviceCpuAbi.sh",
    icon: "Cpu",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "display-logcat",
    name: "查看日志",
    description: "实时查看设备日志输出",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/DisplayLogcat.sh",
    icon: "ScrollText",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名 (可选)",
        required: false,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "run-monkey-test",
    name: "Monkey 测试",
    description: "对指定应用执行 Monkey 随机事件测试",
    category: "device",
    subcategory: "device-basic",
    scriptPath: "shell/device-tools/RunMonkeyTest.sh",
    icon: "Bug",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "应用包名",
        required: true,
      },
      {
        id: "minutes",
        type: "number",
        label: "测试时长(分钟)",
        defaultValue: "5",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },

  // ─── Device - Simulation ─────────────────────────────────────────────
  {
    id: "input-text",
    name: "输入文本",
    description: "向设备输入指定文本内容",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/InputText.sh",
    icon: "Type",
    inputs: [
      {
        id: "text",
        type: "text",
        label: "输入内容",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
    postInputs: ["", "y"],
    postDelayMs: 3000,
  },
  {
    id: "press-back-key",
    name: "模拟返回键",
    description: "模拟按下设备返回键",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/PressBackKey.sh",
    icon: "ArrowLeft",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "press-home-key",
    name: "模拟主页键",
    description: "模拟按下设备主页键",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/PressHomeKey.sh",
    icon: "Home",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "press-menu-key",
    name: "模拟菜单键",
    description: "模拟按下设备菜单键",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/PressMenuKey.sh",
    icon: "Menu",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "press-power-key",
    name: "模拟电源键",
    description: "模拟按下设备电源键",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/PressPowerKey.sh",
    icon: "Power",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "press-task-key",
    name: "模拟多任务键",
    description: "模拟按下设备多任务/最近任务键",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/PressTaskKey.sh",
    icon: "LayoutGrid",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "click-the-screen",
    name: "模拟点击屏幕",
    description: "在屏幕指定坐标位置模拟点击",
    category: "device",
    subcategory: "device-simulation",
    scriptPath: "shell/device-tools/simulation/ClickTheScreen.sh",
    icon: "MousePointer",
    inputs: [
      {
        id: "x",
        type: "number",
        label: "X 坐标",
        required: true,
      },
      {
        id: "y",
        type: "number",
        label: "Y 坐标",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },

  // ─── Device - Env ────────────────────────────────────────────────────
  {
    id: "restart-adb",
    name: "重启 ADB",
    description: "重启 ADB 服务",
    category: "device",
    subcategory: "device-env",
    scriptPath: "shell/device-tools/env/RestartAdb.sh",
    icon: "RefreshCw",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "kill-adb",
    name: "杀死 ADB",
    description: "停止 ADB 服务进程",
    category: "device",
    subcategory: "device-env",
    scriptPath: "shell/device-tools/env/KillAdb.sh",
    icon: "XSquare",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "get-adb-version",
    name: "ADB 版本",
    description: "查看当前 ADB 版本号",
    category: "device",
    subcategory: "device-env",
    scriptPath: "shell/device-tools/env/GetAdbVersion.sh",
    icon: "Info",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "get-fastboot-version",
    name: "Fastboot 版本",
    description: "查看当前 Fastboot 版本号",
    category: "device",
    subcategory: "device-env",
    scriptPath: "shell/device-tools/env/GetFastbootVersion.sh",
    icon: "Info",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["fastboot"],
  },

  // ─── Device - Hardware ───────────────────────────────────────────────
  {
    id: "power-off-device",
    name: "设备关机",
    description: "关闭连接的设备电源",
    category: "device",
    subcategory: "device-hardware",
    scriptPath: "shell/device-tools/hardware/PowerOffDevice.sh",
    icon: "PowerOff",
    inputs: [],
    requiresDevice: true,
    deviceMode: "all",
    multipleDevices: false,
    requiredEnv: ["adb", "fastboot"],
  },
  {
    id: "device-restart",
    name: "设备重启",
    description: "重启连接的设备",
    category: "device",
    subcategory: "device-hardware",
    scriptPath: "shell/device-tools/hardware/DeviceRestart.sh",
    icon: "RotateCw",
    inputs: [],
    requiresDevice: true,
    deviceMode: "all",
    multipleDevices: false,
    requiredEnv: ["adb", "fastboot"],
  },

  // ─── Device - Jump ───────────────────────────────────────────────────
  {
    id: "jump-to-url",
    name: "打开网址",
    description: "在设备浏览器中打开指定网址",
    category: "device",
    subcategory: "device-jump",
    scriptPath: "shell/device-tools/jump/JumpToUrl.sh",
    icon: "ExternalLink",
    inputs: [
      {
        id: "url",
        type: "url",
        label: "网址",
        placeholder: "https://",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "jump-to-activity",
    name: "跳转 Activity",
    description: "启动指定应用的特定 Activity",
    category: "device",
    subcategory: "device-jump",
    scriptPath: "shell/device-tools/jump/JumpToActivity.sh",
    icon: "Navigation",
    inputs: [
      {
        id: "packageName",
        type: "text",
        label: "包名",
        required: true,
      },
      {
        id: "activityName",
        type: "text",
        label: "Activity 名",
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "jump-to-developer-options",
    name: "开发者选项",
    description: "跳转到设备开发者选项页面",
    category: "device",
    subcategory: "device-jump",
    scriptPath: "shell/device-tools/jump/JumpToDeveloperOptions.sh",
    icon: "Settings",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "jump-to-about-device",
    name: "关于手机",
    description: "跳转到设备关于手机页面",
    category: "device",
    subcategory: "device-jump",
    scriptPath: "shell/device-tools/jump/JumpToAboutDevice.sh",
    icon: "Smartphone",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },
  {
    id: "jump-to-wechat",
    name: "打开微信",
    description: "在设备上启动微信应用",
    category: "device",
    subcategory: "device-jump",
    scriptPath: "shell/device-tools/jump/JumpToWechat.sh",
    icon: "MessageCircle",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: true,
    requiredEnv: ["adb"],
  },

  // ─── Device - Flash ──────────────────────────────────────────────────
  {
    id: "read-device-lock",
    name: "读取设备锁",
    description: "读取设备 Bootloader 锁定状态",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/ReadDeviceLock.sh",
    icon: "Lock",
    inputs: [],
    requiresDevice: true,
    deviceMode: "fastboot",
    multipleDevices: false,
    requiredEnv: ["fastboot"],
  },
  {
    id: "restart-to-fastboot",
    name: "重启到 Fastboot",
    description: "将设备重启到 Fastboot 模式",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/RestartToFastboot.sh",
    icon: "Zap",
    inputs: [],
    requiresDevice: true,
    deviceMode: "adb",
    multipleDevices: false,
    requiredEnv: ["adb"],
  },
  {
    id: "restart-to-recovery",
    name: "重启到 Recovery",
    description: "将设备重启到 Recovery 模式",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/RestartToRecovery.sh",
    icon: "RotateCcw",
    inputs: [],
    requiresDevice: true,
    deviceMode: "all",
    multipleDevices: false,
    requiredEnv: ["adb", "fastboot"],
  },
  {
    id: "get-device-code",
    name: "获取机型代号",
    description: "获取设备的机型代号信息",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/GetDeviceCode.sh",
    icon: "Tag",
    inputs: [],
    requiresDevice: true,
    deviceMode: "all",
    multipleDevices: false,
    requiredEnv: ["adb", "fastboot"],
  },
  {
    id: "flash-temp-recovery",
    name: "临时引导 Recovery",
    description: "临时引导自定义 Recovery 镜像（不写入设备）",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/FlashTempRecovery.sh",
    icon: "HardDrive",
    inputs: [
      {
        id: "recoveryFile",
        type: "file",
        label: "Recovery 镜像",
        fileFilters: [{ name: "IMG", extensions: ["img"] }],
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "fastboot",
    multipleDevices: false,
    requiredEnv: ["fastboot"],
  },
  {
    id: "flash-recovery",
    name: "刷写 Recovery",
    description: "将自定义 Recovery 镜像刷写到设备",
    category: "device",
    subcategory: "device-flash",
    scriptPath: "shell/device-tools/flash/FlashRecovery.sh",
    icon: "HardDrive",
    inputs: [
      {
        id: "recoveryFile",
        type: "file",
        label: "Recovery 镜像",
        fileFilters: [{ name: "IMG", extensions: ["img"] }],
        required: true,
      },
    ],
    requiresDevice: true,
    deviceMode: "fastboot",
    multipleDevices: false,
    requiredEnv: ["fastboot"],
  },

  // ─── Reverse - APKTool ───────────────────────────────────────────────
  {
    id: "decompile-apk",
    name: "反编译 APK",
    description: "使用 APKTool 反编译 APK 文件",
    category: "reverse",
    subcategory: "reverse-apktool",
    scriptPath: "shell/reverse-tools/apktool/DecompileApk.sh",
    icon: "Unlock",
    inputs: [
      {
        id: "apkFile",
        type: "file",
        label: "APK 文件",
        fileFilters: [{ name: "APK", extensions: ["apk"] }],
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "recompile-apk",
    name: "回编译 APK",
    description: "使用 APKTool 将反编译目录重新打包为 APK",
    category: "reverse",
    subcategory: "reverse-apktool",
    scriptPath: "shell/reverse-tools/apktool/RecompileApk.sh",
    icon: "Lock",
    inputs: [
      {
        id: "sourceDir",
        type: "directory",
        label: "反编译目录",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },

  // ─── Reverse - Viewer ────────────────────────────────────────────────
  {
    id: "jadx-view",
    name: "Jadx 查看",
    description: "使用 Jadx 查看 APK/DEX/JAR 的 Java 源码",
    category: "reverse",
    subcategory: "reverse-viewer",
    scriptPath: "shell/reverse-tools/jadx/JadxView.sh",
    icon: "Eye",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "APK/DEX/JAR 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "jd-gui-view",
    name: "JD-GUI 查看",
    description: "使用 JD-GUI 查看 JAR/Class 文件的源码",
    category: "reverse",
    subcategory: "reverse-viewer",
    scriptPath: "shell/reverse-tools/jd-gui/JdGuiView.sh",
    icon: "Eye",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "JAR/Class 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },

  // ─── Reverse - Convert ───────────────────────────────────────────────
  {
    id: "dex-to-class",
    name: "DEX 转 Class",
    description: "将 DEX 文件转换为 Class 文件",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/dex-class/DexToClass.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "DEX 文件",
        fileFilters: [{ name: "DEX", extensions: ["dex"] }],
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "class-to-dex",
    name: "Class 转 DEX",
    description: "将 Class 文件或目录转换为 DEX 文件",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/dex-class/ClassToDex.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputPath",
        type: "file",
        label: "Class 文件或目录",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "dex-to-smali",
    name: "DEX 转 Smali",
    description: "将 DEX 文件反汇编为 Smali 代码",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/dex-smali/DexToSmali.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "DEX 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "smali-to-dex",
    name: "Smali 转 DEX",
    description: "将 Smali 代码汇编为 DEX 文件",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/dex-smali/SmaliToDex.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputDir",
        type: "directory",
        label: "Smali 目录",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "jar-to-dex",
    name: "JAR 转 DEX",
    description: "将 JAR 文件转换为 DEX 文件",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/jar-dex/JarToDex.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "JAR 文件",
        fileFilters: [{ name: "JAR", extensions: ["jar"] }],
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "dex-to-jar",
    name: "DEX 转 JAR",
    description: "将 DEX 文件转换为 JAR 文件",
    category: "reverse",
    subcategory: "reverse-convert",
    scriptPath: "shell/reverse-tools/convert/jar-dex/DexToJar.sh",
    icon: "FileCode",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "DEX 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },

  // ─── Package Tools ───────────────────────────────────────────────────
  {
    id: "sign-apk",
    name: "APK 签名",
    description: "对 APK 文件进行签名",
    category: "package",
    scriptPath: "shell/package-tools/SignatureApk.sh",
    icon: "PenTool",
    inputs: [
      {
        id: "apkFile",
        type: "file",
        label: "APK 文件",
        fileFilters: [{ name: "APK", extensions: ["apk"] }],
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "get-apk-signature",
    name: "获取签名信息",
    description: "查看 APK 文件的签名信息",
    category: "package",
    scriptPath: "shell/package-tools/GetApkSignature.sh",
    icon: "FileSearch",
    inputs: [
      {
        id: "apkFile",
        type: "file",
        label: "APK 文件",
        fileFilters: [{ name: "APK", extensions: ["apk"] }],
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "support-to-androidx",
    name: "Support 转 AndroidX",
    description: "将 Support 库依赖转换为 AndroidX",
    category: "package",
    scriptPath: "shell/package-tools/SupportToAndroidX.sh",
    icon: "ArrowRight",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "AAR/JAR 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "androidx-to-support",
    name: "AndroidX 转 Support",
    description: "将 AndroidX 依赖转换回 Support 库",
    category: "package",
    scriptPath: "shell/package-tools/AndroidXToSupport.sh",
    icon: "ArrowLeft",
    inputs: [
      {
        id: "inputFile",
        type: "file",
        label: "AAR/JAR 文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },
  {
    id: "compare-archives",
    name: "包体对比",
    description: "对比两个版本的包体差异",
    category: "package",
    scriptPath: "shell/package-tools/CompareArchives.sh",
    icon: "GitCompare",
    inputs: [
      {
        id: "oldFile",
        type: "file",
        label: "旧版本文件",
        required: true,
      },
      {
        id: "newFile",
        type: "file",
        label: "新版本文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["java"],
  },

  // ─── Git - Repo ──────────────────────────────────────────────────────
  {
    id: "clone-repo",
    name: "克隆仓库",
    description: "克隆远程 Git 仓库到本地",
    category: "git",
    subcategory: "git-repo",
    scriptPath: "shell/git-tools/CloneRepository.sh",
    icon: "Download",
    inputs: [
      {
        id: "repoUrl",
        type: "url",
        label: "仓库地址",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "init-repo",
    name: "初始化仓库",
    description: "在指定目录初始化新的 Git 仓库",
    category: "git",
    subcategory: "git-repo",
    scriptPath: "shell/git-tools/InitRepository.sh",
    icon: "FolderPlus",
    inputs: [
      {
        id: "repoDir",
        type: "directory",
        label: "仓库目录",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "compare-file-diff",
    name: "文件对比",
    description: "对比两个文件的差异",
    category: "git",
    subcategory: "git-repo",
    scriptPath: "shell/git-tools/CompareFileDiff.sh",
    icon: "GitCompare",
    inputs: [
      {
        id: "oldFile",
        type: "file",
        label: "旧文件",
        required: true,
      },
      {
        id: "newFile",
        type: "file",
        label: "新文件",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },

  // ─── Git - Config ────────────────────────────────────────────────────
  {
    id: "open-git-config",
    name: "打开配置文件",
    description: "打开 Git 全局配置文件",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/OpenGitConfigFile.sh",
    icon: "FileText",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "set-optimal-config",
    name: "一键优化配置",
    description: "一键设置推荐的 Git 优化配置",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/SetOptimalConfig.sh",
    icon: "Wand2",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "set-user-name-email",
    name: "设置用户名邮箱",
    description: "设置 Git 全局用户名和邮箱",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/SetUserNameEmailConfig.sh",
    icon: "User",
    inputs: [
      {
        id: "userName",
        type: "text",
        label: "用户名",
        required: true,
      },
      {
        id: "userEmail",
        type: "text",
        label: "邮箱",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "set-encoding-config",
    name: "编码配置",
    description: "设置 Git 字符编码配置",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/SetEncodingConfig.sh",
    icon: "FileCode",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "set-linebreak-config",
    name: "换行符配置",
    description: "设置 Git 换行符处理配置",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/SetLinebreakConfig.sh",
    icon: "WrapText",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "set-filemode-config",
    name: "文件权限配置",
    description: "设置 Git 文件权限跟踪配置",
    category: "git",
    subcategory: "git-config",
    scriptPath: "shell/git-tools/config/SetFileModeConfig.sh",
    icon: "Shield",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },

  // ─── Git - Commit ────────────────────────────────────────────────────
  {
    id: "amend-last-commit-message",
    name: "修改提交信息",
    description: "修改最近一次提交的 commit message",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/amend/AmendLastCommitMessage.sh",
    icon: "Edit",
    inputs: [
      {
        id: "newMessage",
        type: "text",
        label: "新提交信息",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "amend-last-commit-date",
    name: "修改提交时间",
    description: "修改最近一次提交的时间戳",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/amend/AmendLastCommitDate.sh",
    icon: "Clock",
    inputs: [
      { id: "year", type: "number", label: "年", required: true },
      { id: "month", type: "number", label: "月", required: true },
      { id: "day", type: "number", label: "日", required: true },
      { id: "hour", type: "number", label: "时", required: true },
      { id: "minute", type: "number", label: "分", required: true },
      { id: "second", type: "number", label: "秒", required: true },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "amend-last-commit-user-email",
    name: "修改提交作者",
    description: "修改最近一次提交的作者信息",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/amend/AmendLastCommitUserEmail.sh",
    icon: "UserCog",
    inputs: [
      {
        id: "userName",
        type: "text",
        label: "新用户名",
        required: true,
      },
      {
        id: "userEmail",
        type: "text",
        label: "新邮箱",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "rewrite-user-commit-history",
    name: "重写提交历史",
    description: "批量重写指定用户的所有提交历史",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/amend/RewriteUserCommitHistory.sh",
    icon: "History",
    inputs: [
      { id: "oldName", type: "text", label: "旧用户名", required: true },
      { id: "oldEmail", type: "text", label: "旧邮箱", required: true },
      { id: "newName", type: "text", label: "新用户名", required: true },
      { id: "newEmail", type: "text", label: "新邮箱", required: true },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "reset-to-commit",
    name: "重置到提交",
    description: "将当前分支重置到指定的 commit",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/revert/ResetToCommit.sh",
    icon: "RotateCcw",
    inputs: [
      {
        id: "commitHash",
        type: "text",
        label: "Commit Hash",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "revert-commit",
    name: "回滚提交",
    description: "回滚指定的 commit（生成新的 revert 提交）",
    category: "git",
    subcategory: "git-commit",
    scriptPath: "shell/git-tools/commit/revert/RevertCommit.sh",
    icon: "Undo",
    inputs: [
      {
        id: "commitHash",
        type: "text",
        label: "Commit Hash",
        required: true,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },

  // ─── Git - Push ──────────────────────────────────────────────────────
  {
    id: "force-push-branch",
    name: "强制推送分支",
    description: "强制推送当前分支到远程仓库",
    category: "git",
    subcategory: "git-push",
    scriptPath: "shell/git-tools/push/ForcePushBranch.sh",
    icon: "GitBranch",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },
  {
    id: "force-push-tags",
    name: "强制推送标签",
    description: "强制推送所有标签到远程仓库",
    category: "git",
    subcategory: "git-push",
    scriptPath: "shell/git-tools/push/ForcePushTags.sh",
    icon: "Tag",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: ["git"],
  },

  // ─── SSH Key Tools ───────────────────────────────────────────────────
  {
    id: "query-ssh-public-key",
    name: "查看公钥",
    description: "查看本机 SSH 公钥内容",
    category: "ssh-key",
    scriptPath: "shell/ssh-key-tools/QuerySshPublicKey.sh",
    icon: "Eye",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: [],
  },
  {
    id: "create-ssh-key",
    name: "创建密钥",
    description: "创建新的 SSH 密钥对",
    category: "ssh-key",
    scriptPath: "shell/ssh-key-tools/CreateSshKey.sh",
    icon: "Plus",
    inputs: [
      {
        id: "keyName",
        type: "text",
        label: "密钥名称",
        placeholder: "id_ed25519",
        required: false,
      },
    ],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: [],
  },
  {
    id: "delete-ssh-key",
    name: "删除密钥",
    description: "删除本机 SSH 密钥",
    category: "ssh-key",
    scriptPath: "shell/ssh-key-tools/DeleteSshKey.sh",
    icon: "Trash2",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: [],
  },
  {
    id: "open-ssh-key-dir",
    name: "打开密钥目录",
    description: "打开 SSH 密钥所在目录",
    category: "ssh-key",
    scriptPath: "shell/ssh-key-tools/OpenSshKeyDir.sh",
    icon: "FolderOpen",
    inputs: [],
    requiresDevice: false,
    deviceMode: "none",
    multipleDevices: false,
    requiredEnv: [],
  },
];

export function getToolsByCategory(categoryId: string): ToolDefinition[] {
  return tools.filter((t) => t.category === categoryId);
}

export function getToolsBySubcategory(subcategoryId: string): ToolDefinition[] {
  return tools.filter((t) => t.subcategory === subcategoryId);
}

export function getToolById(id: string): ToolDefinition | undefined {
  return tools.find((t) => t.id === id);
}

export function searchTools(query: string): ToolDefinition[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (terms.length === 0) return tools;

  return tools.filter((tool) => {
    const haystack = `${tool.name} ${tool.description} ${tool.id}`.toLowerCase();
    return terms.every((term) => haystack.includes(term));
  });
}
